spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo
    username: root
    password: root
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    initialize: true